### ISSUE TITLE
Projectsにコラボレーターの追加

### ISSUE THREAD

**Issue by pchan1111** [seki-shu/Group15_Multimodal#1]
Projectsで進捗管理ができるっぽいのですが、どうやら権限がないとプロジェクトを作成できないようなので、コラボレーターの追加をお願いします！
[https://mocotan.hatenablog.com/entry/2022/04/06/021801](url)

**Comment by seki-shu** [comment]
作成してコラボレータ追加してみました，確認お願いします！

**Comment by pchan1111** [comment]
できました！ありがとうございます。
